<a href="https://colab.research.google.com/github/abhinavtk1/ED5340-CW/blob/main/MA23M002_Feb26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Python libraries

In [6]:
# pandas
import pandas as pd
data = pd.read_csv('test.csv')

In [16]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>


In [8]:
print(data)

   x   y
0  a   1
1  b   2
2  c   3
3  d   4
4  e   5
5  f   6
6  g   7
7  h   8
8  i   9
9  j  10


In [9]:
data.columns

Index(['x', 'y'], dtype='object')

In [10]:
print(data['x'])

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
Name: x, dtype: object


In [11]:
print(data['y'])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: y, dtype: int64


In [12]:
list1 = list(data['x'])

In [13]:
list1

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [14]:
# Numpy

In [19]:
import numpy as np
print(np.__version__)

1.25.2


In [20]:
# 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Numpy Array:")
print(arr)

Numpy Array:
[1 2 3 4 5]


In [21]:
print(arr.itemsize, arr.strides)

8 (8,)


In [22]:
arr2 = np.array([[3,5,3,2,4], [3,5,6,3,1]])

In [24]:
print(arr2.ndim, arr2.size, arr2.dtype, arr2.itemsize, arr2.data)

2 10 int64 8 <memory at 0x7f3abed8eb50>


In [25]:
e = np.arange(15).reshape(5,3)

In [26]:
e

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
import math
a = np.linspace(0, 2, 9)
b = np.linspace(0, 2*math.pi, 100)
c = np.sin(b)

In [30]:
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [31]:
print(b)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [32]:
print(c)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

In [34]:
print(b-c)

[0.00000000e+00 4.25985978e-05 3.40582935e-04 1.14831040e-03
 2.71808584e-03 5.29914557e-03 9.13665387e-03 1.44707157e-02
 2.15354099e-02 3.05578468e-02 4.17572535e-02 5.53440911e-02
 7.15192076e-02 9.04730286e-02 1.12384791e-01 1.37421822e-01
 1.65738862e-01 1.97477447e-01 2.32765333e-01 2.71715987e-01
 3.14428124e-01 3.60985315e-01 4.11455649e-01 4.65891455e-01
 5.24329099e-01 5.86788829e-01 6.53274699e-01 7.23774551e-01
 7.98260065e-01 8.76686871e-01 9.58994729e-01 1.04510777e+00
 1.13493481e+00 1.22836970e+00 1.32529177e+00 1.42556630e+00
 1.52904508e+00 1.63556700e+00 1.74495869e+00 1.85703523e+00
 1.97160087e+00 2.08844986e+00 2.20736724e+00 2.32812975e+00
 2.45050666e+00 2.57426076e+00 2.69914931e+00 2.82492496e+00
 2.95133683e+00 3.07813146e+00 3.20505385e+00 3.33184847e+00
 3.45826035e+00 3.58403600e+00 3.70892454e+00 3.83267865e+00
 3.95505556e+00 4.07581806e+00 4.19473545e+00 4.31158444e+00
 4.42615008e+00 4.53822661e+00 4.64761830e+00 4.75414022e+00
 4.85761901e+00 4.957893

In [35]:
print(np.sin(a))

[0.         0.24740396 0.47942554 0.68163876 0.84147098 0.94898462
 0.99749499 0.98398595 0.90929743]


In [37]:
a1 = np.array(([1,2], [3,4]))
b1 = np.array(([1, 2], [3, 4]))

In [38]:
print(a1*b1)

[[ 1  4]
 [ 9 16]]


In [40]:
print(a1 @ b1)

[[ 7 10]
 [15 22]]


In [41]:
print(np.dot(a1,b1))

[[ 7 10]
 [15 22]]


In [43]:
print(a1[0].dot(b1[0]))

5
